# Generated by Django 4.2 on 2024-05-07 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments_like',
            new_name='comments_likes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comments_upvote',
            new_name='comments_upvotes',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_like',
            new_name='reply_likes',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='reply_upvote',
            new_name='reply_upvotes',
        ),
    ]
