# Generated by Django 4.2 on 2024-05-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_comments_like_comment_comments_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='conment',
        ),
    ]
