# Generated by Django 4.2 on 2024-05-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_content_comment_conment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conment',
            new_name='conments',
        ),
    ]
