services:
  web:
    build: .
    command: gunicorn spartanews.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/spartanews
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://tmoon:jqjqjqjq@db:5432/postgres
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: tmoon
      POSTGRES_PASSWORD: jqjqjqjq

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
